var myFullName;
myFullName = "Latika Bagal";
console.log(myFullName);
myFullName = "Latika Gorakh Bagal";
console.log(myFullName);
var myLove;
myLove ="I love only JS";
console.log(myLove);
var firstName ="Latika";
var lastName ="Bagal";
var age = "25";
var address = "Velapur Tal Malshiras Dist-Solapur";
var pin_code = "413113";
var gender = "Female";
var is_married = "Yes";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(pin_code);
console.log(gender);
console.log(is_married);